# Generated by Django 5.1.6 on 2025-02-18 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('propietario', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('absuelto', 'Absuelto'), ('pagado', 'Pagado'), ('no_pagado', 'No Pagado'), ('anulado', 'Anulado'), ('en_proceso', 'En Proceso')], max_length=50)),
                ('fecha_reg', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('cat_licen', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Apelacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.TextField()),
                ('documentos', models.FileField(upload_to='apelaciones/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actas.acta')),
            ],
        ),
        migrations.CreateModel(
            name='Infraccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_infrac', models.DateTimeField()),
                ('retencion', models.CharField(max_length=50)),
                ('id_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actas.conductor')),
                ('id_vehiculo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='actas.vehiculo')),
            ],
        ),
        migrations.AddField(
            model_name='acta',
            name='id_infrac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actas.infraccion'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254)),
                ('psw', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='acta',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actas.usuario'),
        ),
    ]
