# Generated by Django 5.1.6 on 2025-02-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0003_alter_acta_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='acta',
            name='test',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
