# Generated by Django 5.1.6 on 2025-02-18 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0004_acta_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acta',
            name='test',
        ),
    ]
