# Generated by Django 5.1.6 on 2025-03-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0007_vehiculo_marca_vehiculo_modelo_alter_vehiculo_placa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='modelo',
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(max_length=10),
        ),
    ]
