# Generated by Django 5.1.6 on 2025-03-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0008_remove_vehiculo_marca_remove_vehiculo_modelo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acta',
            name='estado_apelacion',
            field=models.CharField(choices=[('En proceso', 'En proceso'), ('Absuelto', 'Absuelto'), ('Rechazado', 'Rechazado')], default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='acta',
            name='estado',
            field=models.CharField(choices=[('Pagado', 'Pagado'), ('No pagado', 'No Pagado')], max_length=50),
        ),
    ]
