# Generated by Django 5.1.6 on 2025-03-03 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0009_acta_estado_apelacion_alter_acta_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='image',
        ),
    ]
